apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: my-app-prod
  namespace: argocd

spec:
  project: platform-project

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-prod

  sources:

    - repoURL: ghcr.io/debnil001
      targetRevision: 0.1.0
      chart: my-app
      
      helm:
        valueFiles:
        - $values/environments/my-app/prod/values.yaml


    - repoURL: https://github.com/debnil001/argocd-demo-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
