
replicaCount: 3

image:
  repository: my-app
  tag: v2
  pullPolicy: IfNotPresent

app:
  version: prod

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
