apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: my-app-dev
  namespace: argocd

spec:
  project: platform-project

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-dev

  sources:

    - repoURL: https://github.com/debnil001/app-repo.git
      targetRevision: main
      path: my-app
      
      helm:
        valueFiles:
        - $values/environments/my-app/dev/values.yaml


    - repoURL: https://github.com/debnil001/gitops-repo.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
